### ISSUE TITLE
Неправильная успеваемость

### ISSUE THREAD

**Issue by Pandem1r** [brstu/MMIPU-2022#202]
Горчинский. Сданы и приняты вами все лабораторные работы 1-4, но в успеваемости отмечены только 1 и 2. Прошу исправить.
![изображение](https://user-images.githubusercontent.com/92267602/209667417-184dd1c1-e274-42e8-9de2-e6b676ee2be9.png)
Вот скриншот с подтверждением того, что сдал все лабораторные работы.
![изображение](https://user-images.githubusercontent.com/92267602/209667580-1c17005b-80f0-4313-a92c-3910b094ddc0.png)

**Comment by fakehomer** [comment]
Дубяга. Такая же проблема, 4 работа сдана и принята ещё до начала сессии. 
<img width="889" alt="Снимок" src="https://user-images.githubusercontent.com/92292715/209691961-4a7f7e20-2e90-47a8-a5ca-80baa139b630.PNG">
<img width="573" alt="Снимок2" src="https://user-images.githubusercontent.com/92292715/209691964-2bbf2dff-b9e4-42f1-a958-6261f1c104a5.PNG">
